version: '3.8'

volumes:
  pgdata:

services:
  app:
    build: .  # указывает Docker собирать образ из текущей директории
    ports:
      - "8080:8080"  # открывает порт 8080 на хосте, перенаправляя его в контейнер
    depends_on:  # указывает, что контейнер приложения зависит от контейнеров: 'db' и 'redis'
      - db
      - redis

  db:
    container_name: cinemate-db
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_DB: cinemate-docker
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: admin
    ports:
      - "5438:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    container_name: cinemate-redis
    image: redis:7
    restart: always
    ports:
      - "6389:6379"
