spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cinemate_test
    username: postgres
    password: dansob_2004
    driverClassName: org.postgresql.Driver

  flyway:
    enabled: true
    user: postgres
    password: dansob_2004
    schemas: public
    url: jdbc:postgresql://localhost:5432/cinemate_test

db_data:
  surname: src/main/resources/data/surname.txt
  username: src/main/resources/data/username.txt

admin_data:
  password: $2a$10$e.lC9uZMHSaOBHjgRFMUJen3TBJLrroMIcxpeBQKB6j8dZbDsBIYG
  role: ROLE_ADMIN

user_data:
  password: $2a$10$uHVMb6KYlogP7T4C0UPLZ.mkR2zmh4eM/rxPk82KQ76.3bmV8uYGC
  role: ROLE_USER
