spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cinemate_test
    username: postgres
    password: "********************"
    driverClassName: org.postgresql.Driver

  flyway:
    enabled: true
    user: "********************"
    password: "********************"
    schemas: public
    url: jdbc:postgresql://localhost:5432/cinemate_test

  redis:
    host: localhost
    port: 6379
    timeout: 60000  # 60 seconds

base:
  root_path: src/main/resources/

db_data:
  surname: src/main/resources/data/surname.txt
  username: src/main/resources/data/username.txt
  content_types: src/main/resources/data/content_types.txt
  warnings: src/main/resources/data/warnings.txt
  actors: src/main/resources/data/actors.txt
  genres: src/main/resources/data/genres.txt
  content_names: src/main/resources/data/content/names.txt
  content_posters: src/main/resources/data/content/posters.txt
  content_trailers: src/main/resources/data/content/trailers.txt
  delete_tables_sql: src/main/resources/db_data/delete_tables.sql