DROP TABLE IF EXISTS externalauth CASCADE;
DROP TABLE IF EXISTS userrole CASCADE;
DROP TABLE IF EXISTS appuser CASCADE;
DROP TABLE IF EXISTS role CASCADE;
DROP TABLE IF EXISTS contenttype CASCADE;
DROP TABLE IF EXISTS warning CASCADE;
DROP TABLE IF EXISTS actor CASCADE;
DROP TABLE IF EXISTS genre CASCADE;