DROP TABLE IF EXISTS externalauth CASCADE;
DROP TABLE IF EXISTS userrole CASCADE;
DROP TABLE IF EXISTS appuser CASCADE;
DROP TABLE IF EXISTS authprovider CASCADE;
DROP TABLE IF EXISTS role CASCADE;

DROP TABLE IF EXISTS wishlist CASCADE;
DROP TABLE IF EXISTS contentgenre CASCADE;
DROP TABLE IF EXISTS contentactor CASCADE;
DROP TABLE IF EXISTS contentwarning CASCADE;
DROP TABLE IF EXISTS episode CASCADE;
DROP TABLE IF EXISTS content CASCADE;
DROP TABLE IF EXISTS warning CASCADE;
DROP TABLE IF EXISTS actor CASCADE;
DROP TABLE IF EXISTS genre CASCADE;
DROP TABLE IF EXISTS contenttype CASCADE;
